### ISSUE TITLE
Cannot build project or use readyapi4j in a maven projecet

### ISSUE THREAD

**Issue by MarcoTorres-Hexaware** [SmartBear/readyapi4j#125]
When trying to build the project I get a dependency error: 
"Could not find artifact com.smartbear.soapui:soapui-testserver-api:pom:5.6.0-SNAPSHOT in smartbear.public (http://smartbearsoftware.com/repository/maven2/)"
It actually seems that version is not in the repo:
![image](https://user-images.githubusercontent.com/61030750/78964315-63354880-7abf-11ea-9637-dd86f5732500.png)

Also when trying to use on a maven project dependencies are not found:
"Failure to find com.smartbear.readyapi:readyapi4j-facade:pom:1.0.0-SNAPSHOT in http://smartbearsoftware.com/repository/maven2/". Same as previous I could not find dependency browsing private repo:
![image](https://user-images.githubusercontent.com/61030750/78964369-8c55d900-7abf-11ea-953b-c0c7968ead6b.png)

Any suggestions, do I need access to a private maven server?

Thanks in advance

**Comment by olensmar** [comment]
Hi @MarcoTorres-Hexaware - thanks for reaching out. Could you try to build the https://github.com/olensmar/soapui/tree/testserver-api-update branch (this hasn't been merged back to the smartbear repo yet) - which should give you the 5.6.0-SNAPSHOT dependencies...

**Comment by MarcoTorres-Hexaware** [comment]
Thanks @olensmar will try and update on the results. Appreciate the prompt response.

**Comment by MarcoTorres-Hexaware** [comment]
@olensmar Thanks, that helped a lot, I was able to build. But I had to skip tests, it looks like it was looking for a local server in port 8080 to get some wdsl, which mvn clean install was not raising, I probably was using an incorrect profile, I will double check on this, but for now I was able to build. Thanks again

**Comment by olensmar** [comment]
Great - thanks for confirming @MarcoTorres-Hexaware - I'll look into the test issue also... Please don't hesitate to raise more issues!

**Comment by MarcoTorres-Hexaware** [comment]
@olensmar I realized my comment might not be clear regarding which project I had issues on the tests, the project I had issues building was the branch you shared for soapui project (https://github.com/olensmar/soapui/tree/testserver-api-update),  readyapi4j can build without issues, tests on this project are not failing
