### ISSUE TITLE
Implement pattern assertion inside result

### ISSUE THREAD

**Issue by Art1k** [SmartBear/readyapi4j#20]
It would be nice if you add and assertion that will be able to look through response\results by patern.
For example if i have json that consists of json aray with dynamic names or without them e.g.

```
{"eventId":450079,"ehsInternalEventTS":"2016-04-13 14:39:00.682 GMT","cId":23762730,"metriUid":"S1Ma9pVDxiPQxb=","appSource":mopbile,"creationDate":"2016-04-13 16:38:06.957 GMT","language":"ENGLISH","country":"Germany","registrationIp":"190.97.15.187","clientType":null,"marketingParameters":{"trafficSource.network":""trafficSource.trafficId":"69211","trafficSource.media":"MediaSource"},"eventType":"LEAD"},
```

So i'd like to verify that $.*.cid = mySubmittedID

**Comment by olensmar** [comment]
@prakashmrec @spindelmanne does the JsonPath library we use support wildcards like this?!

**Comment by prakashmrec** [comment]
You can use "JsonPath Match Assertion" with JSONPath expression: "$.cId" and using the property expansion for expected value.
