### ISSUE TITLE
Add extractor methods to teststeps

### ISSUE THREAD

**Issue by olensmar** [SmartBear/readyapi4j#46]
It is sometimes needed to extract a value from the outcome/response of a TestStep and reuse that in the java code itself - for example if a response contains an ID or header that one wants to reuse for other purposes. Currently one can achieve this by accessing the underlying transaction log support and then parse that manually. 

To simplify for the client I suggest we add "extractor methods" that can be added to teststeps as  follows;

``` java
TestRecipe recipe = newTestRecipe()
            .addStep(
                getRequest("...")
                    .<configuration methods>
                    .extractFromResponse("<some path expression>", e -> (lambda function handling the value)
            )
            .buildTestRecipe();

client.createRecipeExecutor().executeRecipe(recipe)
```

Running the above would run the recipe and call the lambda function with the extracted value once the result has been received. We could start by adding these methods to HTTP-related requests;
- extractFromResponse( pathExpression, <lambda> )
- extractHeader( headerName, <lambda> )

@prakashmrec @veinSmart @spindelmanne thoughts on this?

**Comment by veinSmart** [comment]
Hi

Yes, this sounds like a good idea. It gives reusability for information in the testrecipies and that is always good in my book.

And definitely doable. Although, I am still not really sure about all of the inner workings of the TestRecipe yet, it should be just to add a method to it, something like:

private final Supplier<? extends T> supplier;

public void extractFromResponse(Supplier <? extends T> supplier){
   this.supplier = supplier
}

and then just have a method where we execute the lambda when appropriate:

public T execute(){
    return this.supplier.get();
}

Or something similar :)

**Comment by olensmar** [comment]
sounds good - I think the main challenge is perhaps how to execute the path statements; 
* if we do it in the client we'll have to pull in dependencies for jsonpath and xpath and run these after the result has been received (also for async executions)
* if we do it on the server we'll have to somehow "augment" the recipe to include property-transfers and properties holding the extracted values that we can then get from the client!?
  * doing it on the server has the advantage of not requiring client libraries - and allowing support for regular property-expansions!?

**Comment by veinSmart** [comment]
I like the server solution better, since I wouldn't want to add a dependency to the client if not absolutely necessary. 

But we need to put some thinking into it so that we dont paint ourselves in a corner...

**Comment by prakashmrec** [comment]
So, I assume that this transfer is within a recipe, from one step to another one. Then I think we should extend existing property transfer test step if it's not enough or the property expansion mechanism. Do you have an exmaple where existing property transfer test step is not enough ?

**Comment by prakashmrec** [comment]
It has been implemented in PR: https://github.com/SmartBear/readyapi4j/pull/49
